import type {
  Source,
  Category,
  Lesson,
  TrainingPlan,
  TrainingSession,
  Exercise,
  ProgressLog,
  UserGoal,
  User,
  UserProfile,
  AdminDashboardStats,
  UserDashboardData,
  IngestionJob,
} from "@/types";

// ── Categories / Taxonomy ──

export const categories: Category[] = [
  { id: "cat-1", name: "Forehand", slug: "forehand", sortOrder: 1, icon: "🎾", description: "All forehand technique and drills", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-2", name: "Backhand", slug: "backhand", sortOrder: 2, icon: "🎾", description: "One-hand and two-hand backhand", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-3", name: "Serve", slug: "serve", sortOrder: 3, icon: "🎾", description: "Flat, kick, and slice serves", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-4", name: "Return", slug: "return", sortOrder: 4, icon: "🎾", description: "Return of serve strategies", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-5", name: "Volley", slug: "volley", sortOrder: 5, icon: "🎾", description: "Net play and volley technique", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-6", name: "Footwork", slug: "footwork", sortOrder: 6, icon: "👟", description: "Movement patterns and agility", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-7", name: "Court Positioning", slug: "court-positioning", sortOrder: 7, icon: "📐", description: "Strategic court coverage", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-8", name: "Biomechanics", slug: "biomechanics", sortOrder: 8, icon: "🦴", description: "Body mechanics and injury prevention", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-9", name: "Conditioning", slug: "conditioning", sortOrder: 9, icon: "💪", description: "Physical fitness and endurance", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-10", name: "Tactics & Strategy", slug: "tactics-strategy", sortOrder: 10, icon: "🧠", description: "Match tactics and game plans", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-11", name: "Mental Training", slug: "mental-training", sortOrder: 11, icon: "🧘", description: "Focus, resilience, and match psychology", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-12", name: "Drills", slug: "drills", sortOrder: 12, icon: "🔄", description: "Practice drills for all levels", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-13", name: "Equipment", slug: "equipment", sortOrder: 13, icon: "🏸", description: "Rackets, strings, and gear", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-14", name: "Doubles", slug: "doubles", sortOrder: 14, icon: "👥", description: "Doubles strategy and positioning", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-15", name: "Slice & Spin", slug: "slice-spin", sortOrder: 15, icon: "🌀", description: "Topspin, slice, and spin techniques", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-16", name: "Recovery", slug: "recovery", sortOrder: 16, icon: "🧊", description: "Recovery, stretching, and mobility", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-17", name: "Grip", slug: "grip", sortOrder: 17, icon: "✋", description: "Grip types and transitions", createdAt: "2025-01-15T10:00:00Z" },
  { id: "cat-18", name: "Mobility", slug: "mobility", sortOrder: 18, icon: "🤸", description: "Flexibility and mobility work", createdAt: "2025-01-15T10:00:00Z" },
];

// ── Sources ──

export const sources: Source[] = [
  {
    id: "src-1",
    title: "The Inner Game of Tennis",
    sourceType: "pdf",
    author: "W. Timothy Gallwey",
    categoryId: "cat-11",
    skillLevel: "intermediate",
    tags: ["mental", "psychology", "classic"],
    status: "active",
    visibility: "public",
    ingestionState: "completed",
    trustLevel: "trusted",
    fileSize: 2400000,
    description: "Classic mental game approach to tennis mastery",
    summary: "Foundational text on the mental approach to tennis performance. Covers Self 1 vs Self 2 concepts, letting go of judgment, and achieving flow state during play.",
    chunkCount: 142,
    createdAt: "2025-02-10T08:30:00Z",
    updatedAt: "2025-03-01T14:20:00Z",
  },
  {
    id: "src-2",
    title: "Winning Ugly — Brad Gilbert",
    sourceType: "pdf",
    author: "Brad Gilbert",
    categoryId: "cat-10",
    skillLevel: "advanced",
    tags: ["tactics", "strategy", "match-play"],
    status: "active",
    visibility: "public",
    ingestionState: "completed",
    trustLevel: "trusted",
    fileSize: 3100000,
    description: "Mental warfare and smart tactics for competitive tennis",
    summary: "Tactical playbook for competitive players. Covers opponent analysis, pattern exploitation, and strategic shot selection in match situations.",
    chunkCount: 198,
    createdAt: "2025-02-12T09:00:00Z",
    updatedAt: "2025-03-05T11:15:00Z",
  },
  {
    id: "src-3",
    title: "Modern Forehand Biomechanics — ATP Analysis",
    sourceType: "youtube",
    author: "Tennis Analytics Lab",
    categoryId: "cat-1",
    skillLevel: "advanced",
    tags: ["forehand", "biomechanics", "atp", "technique"],
    status: "active",
    visibility: "public",
    ingestionState: "completed",
    trustLevel: "trusted",
    sourceUrl: "https://youtube.com/watch?v=example1",
    description: "Detailed biomechanical analysis of modern ATP forehands",
    summary: "Video analysis covering kinetic chain activation, racket lag, contact point optimization, and follow-through patterns in modern professional forehands.",
    chunkCount: 34,
    createdAt: "2025-03-01T15:00:00Z",
    updatedAt: "2025-03-15T09:30:00Z",
  },
  {
    id: "src-4",
    title: "Tennis Footwork Patterns — Complete Guide",
    sourceType: "website",
    author: "Elite Tennis Academy",
    categoryId: "cat-6",
    skillLevel: "intermediate",
    tags: ["footwork", "movement", "agility", "patterns"],
    status: "active",
    visibility: "public",
    ingestionState: "completed",
    trustLevel: "trusted",
    sourceUrl: "https://elitetennisacademy.com/footwork-guide",
    description: "Comprehensive footwork pattern guide for competitive players",
    summary: "Covers split step timing, recovery steps, approach steps, and lateral movement patterns used by professional players.",
    chunkCount: 56,
    createdAt: "2025-03-10T11:00:00Z",
    updatedAt: "2025-03-20T16:45:00Z",
  },
  {
    id: "src-5",
    title: "Serve Mechanics — From Beginner to Advanced",
    sourceType: "pdf",
    author: "Coach Mike Trent",
    categoryId: "cat-3",
    skillLevel: "beginner",
    tags: ["serve", "technique", "progression"],
    status: "active",
    visibility: "public",
    ingestionState: "processing",
    trustLevel: "unreviewed",
    fileSize: 1800000,
    description: "Progressive serve development from scratch to tournament-ready",
    summary: "Step-by-step serve progression covering grip, toss, trophy position, pronation, and placement strategies.",
    chunkCount: 0,
    createdAt: "2025-04-01T08:00:00Z",
    updatedAt: "2025-04-01T08:00:00Z",
  },
  {
    id: "src-6",
    title: "Tactical Patterns in Modern Tennis",
    sourceType: "manual",
    author: "MATCHPOINT Team",
    categoryId: "cat-10",
    skillLevel: "advanced",
    tags: ["tactics", "patterns", "rally"],
    status: "active",
    visibility: "private",
    ingestionState: "completed",
    trustLevel: "trusted",
    description: "Internal notes on tactical patterns observed in professional matches",
    summary: "Collection of rally construction patterns, approach shot setups, and pressure sequences commonly used in high-level match play.",
    chunkCount: 23,
    createdAt: "2025-03-25T14:00:00Z",
    updatedAt: "2025-04-05T10:00:00Z",
  },
  {
    id: "src-7",
    title: "Return of Serve Masterclass",
    sourceType: "youtube",
    author: "Pro Tennis Coaching",
    categoryId: "cat-4",
    skillLevel: "intermediate",
    tags: ["return", "positioning", "read"],
    status: "inactive",
    visibility: "public",
    ingestionState: "failed",
    trustLevel: "untrusted",
    sourceUrl: "https://youtube.com/watch?v=example2",
    description: "Analysis of return of serve techniques",
    errorMessage: "Failed to extract audio transcript — video unavailable",
    chunkCount: 0,
    createdAt: "2025-04-02T12:00:00Z",
    updatedAt: "2025-04-02T12:30:00Z",
  },
  {
    id: "src-8",
    title: "Periodization for Tennis Athletes",
    sourceType: "pdf",
    author: "Dr. Sarah Chen",
    categoryId: "cat-9",
    skillLevel: "elite",
    tags: ["conditioning", "periodization", "strength", "endurance"],
    status: "active",
    visibility: "public",
    ingestionState: "pending",
    trustLevel: "unreviewed",
    fileSize: 4200000,
    description: "Scientific approach to training periodization for competitive tennis",
    chunkCount: 0,
    createdAt: "2025-04-08T07:00:00Z",
    updatedAt: "2025-04-08T07:00:00Z",
  },
];

// ── Ingestion Jobs ──

export const ingestionJobs: IngestionJob[] = [
  {
    id: "job-1",
    sourceId: "src-5",
    status: "processing",
    startedAt: "2025-04-01T08:05:00Z",
    chunksCreated: 0,
    metadata: { parser: "pdf", pages: 45 },
    createdAt: "2025-04-01T08:00:00Z",
  },
  {
    id: "job-2",
    sourceId: "src-7",
    status: "failed",
    startedAt: "2025-04-02T12:05:00Z",
    completedAt: "2025-04-02T12:30:00Z",
    chunksCreated: 0,
    errorMessage: "Failed to extract audio transcript — video unavailable",
    metadata: { parser: "youtube" },
    createdAt: "2025-04-02T12:00:00Z",
  },
  {
    id: "job-3",
    sourceId: "src-8",
    status: "pending",
    chunksCreated: 0,
    metadata: { parser: "pdf", pages: 78 },
    createdAt: "2025-04-08T07:00:00Z",
  },
];

// ── Users ──

export const adminUser: User = {
  id: "usr-admin-1",
  email: "admin@matchpoint.app",
  name: "Alex Rivera",
  role: "admin",
  avatarUrl: undefined,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-04-01T10:00:00Z",
};

export const demoUser: User = {
  id: "usr-1",
  email: "marcus@example.com",
  name: "Marcus Chen",
  role: "user",
  avatarUrl: undefined,
  createdAt: "2025-02-15T09:00:00Z",
  updatedAt: "2025-04-05T11:00:00Z",
};

export const demoProfile: UserProfile = {
  id: "prof-1",
  userId: "usr-1",
  age: 28,
  gender: "male",
  country: "United States",
  timezone: "America/New_York",
  tennisLevel: "intermediate",
  yearsPlaying: 4,
  dominantHand: "right",
  currentGoals: ["Improve serve consistency", "Better net approach", "Build match endurance"],
  availableTrainingDays: 4,
  availableMinutesPerSession: 90,
  hasCourtAccess: true,
  hasCoachAccess: false,
  hasBallMachine: true,
  physicalLimitations: "Minor right shoulder tightness",
  fitnessLevel: "high",
  preferredLearningStyle: "visual",
  preferredPlanIntensity: "intense",
  onboardingCompleted: true,
  createdAt: "2025-02-15T09:30:00Z",
  updatedAt: "2025-04-01T14:00:00Z",
};

// ── Lessons ──

export const lessons: Lesson[] = [
  {
    id: "les-1",
    title: "Modern Forehand Fundamentals",
    slug: "modern-forehand-fundamentals",
    description: "Build a powerful, reliable forehand with proper technique from the ground up.",
    categoryId: "cat-1",
    skillLevel: "beginner",
    tags: ["forehand", "technique", "fundamentals"],
    estimatedMinutes: 25,
    sortOrder: 1,
    isPublished: true,
    content: {
      explanation: "The modern forehand is the most important weapon in tennis. It relies on a semi-western or western grip, a unit turn that engages the full kinetic chain, and a low-to-high swing path that generates topspin naturally. Unlike the classic forehand, the modern version uses an open or semi-open stance, allowing for faster recovery and more power from the legs.",
      keyPoints: [
        "Use a semi-western grip for optimal topspin and power balance",
        "Initiate the stroke with a full unit turn — shoulders, hips, and feet working together",
        "Keep the non-dominant hand on the throat of the racket during the take-back",
        "Contact the ball slightly in front of your lead hip",
        "Follow through over the opposite shoulder with full extension",
        "Maintain a relaxed grip pressure (3-4 out of 10) until contact",
      ],
      steps: [
        { title: "The Grip", description: "Place the base knuckle of your index finger on bevel 4 (semi-western). The heel pad should rest on the same bevel. This grip naturally closes the racket face for topspin." },
        { title: "Ready Position", description: "Stand with feet shoulder-width apart, knees slightly bent, weight on the balls of your feet. Hold the racket at waist height with both hands." },
        { title: "Unit Turn", description: "As the ball approaches your forehand side, rotate your shoulders and hips sideways. The racket goes back as one unit with your body — don't pull it back with your arm alone." },
        { title: "Forward Swing", description: "Drop the racket head below the incoming ball. Drive forward with your legs and rotate your hips, then shoulders. The arm follows the body rotation." },
        { title: "Contact Point", description: "Strike the ball at waist height, slightly in front of your lead hip. The racket face should be slightly closed at contact for natural topspin." },
        { title: "Follow-Through", description: "Continue the swing upward and across your body. Finish with the racket over your opposite shoulder. The wrist should pronate naturally through the shot." },
      ],
      commonMistakes: [
        "Arm-only swing without body rotation",
        "Gripping too tightly throughout the stroke",
        "Late contact point — hitting beside or behind the body",
        "Not dropping the racket head below the ball before contact",
        "Standing straight up instead of loading the legs",
      ],
      recommendedDrills: [
        "Shadow swings with unit turn emphasis (3 sets of 20)",
        "Drop-feed forehands focusing on contact point (50 balls)",
        "Rally drill: crosscourt forehands only (15 min)",
        "Target practice: place cones at baseline corners",
      ],
      relatedLessonIds: ["les-3", "les-5"],
    },
    createdAt: "2025-01-20T10:00:00Z",
    updatedAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "les-2",
    title: "One-Handed Backhand Technique",
    slug: "one-handed-backhand-technique",
    description: "Master the elegant one-handed backhand with proper timing and drive.",
    categoryId: "cat-2",
    skillLevel: "intermediate",
    tags: ["backhand", "one-handed", "technique"],
    estimatedMinutes: 30,
    sortOrder: 2,
    isPublished: true,
    content: {
      explanation: "The one-handed backhand is a technically demanding but rewarding stroke. It offers exceptional reach, natural slice capability, and beautiful aesthetics when executed well. The key is in the shoulder turn, grip change speed, and timing the release of the non-dominant hand.",
      keyPoints: [
        "Use an eastern backhand grip for flat/topspin shots",
        "The non-dominant hand guides the racket during the take-back",
        "Shoulder turn must be deeper than the forehand",
        "Contact point is further in front than the forehand",
        "Maintain a firm wrist through contact",
        "Full extension through the ball creates depth and power",
      ],
      steps: [
        { title: "Grip Change", description: "Rotate to an eastern backhand grip — base knuckle on bevel 1. Practice quick grip changes from the ready position." },
        { title: "Take-Back", description: "Turn both shoulders sideways, guiding the racket back with the non-dominant hand on the throat. The racket should be at shoulder height." },
        { title: "Forward Swing", description: "Release the non-dominant hand and drive forward. Lead with the edge of the racket, letting the arm extend fully toward the target." },
        { title: "Contact & Follow-Through", description: "Strike at full extension in front of your lead hip. Follow through high and across, finishing with the racket pointing at the target." },
      ],
      commonMistakes: [
        "Insufficient shoulder turn",
        "Dropping the elbow during the swing",
        "Not releasing the non-dominant hand early enough",
        "Hitting with a bent arm instead of full extension",
      ],
      recommendedDrills: [
        "Shadow stroke with full shoulder turn (3 sets of 15)",
        "Feed drill: crosscourt backhands (40 balls)",
        "Wall rally: backhand only (10 min)",
      ],
      relatedLessonIds: ["les-1"],
    },
    createdAt: "2025-01-25T10:00:00Z",
    updatedAt: "2025-03-10T14:00:00Z",
  },
  {
    id: "les-3",
    title: "Building a Reliable Serve",
    slug: "building-reliable-serve",
    description: "Develop a consistent, powerful serve with correct mechanics and placement.",
    categoryId: "cat-3",
    skillLevel: "beginner",
    tags: ["serve", "technique", "toss", "pronation"],
    estimatedMinutes: 35,
    sortOrder: 3,
    isPublished: true,
    content: {
      explanation: "The serve is the most important shot in tennis — it's the only stroke you have complete control over. A reliable serve starts with a consistent toss, moves through a fluid motion, and finishes with proper pronation for power and spin. Building muscle memory through repetition is essential.",
      keyPoints: [
        "Continental grip is mandatory for all serve types",
        "The toss determines the serve type — master a consistent toss first",
        "Trophy position: racket up, elbow high, weight loaded",
        "Pronation is the key to power and spin — not arm speed",
        "The legs provide 50%+ of serve power",
        "Aim for placement and consistency before adding power",
      ],
      steps: [
        { title: "Grip & Stance", description: "Use a continental grip (base knuckle on bevel 2). Stand sideways to the baseline with your front foot pointing toward the net post." },
        { title: "The Toss", description: "Hold the ball in your fingertips, not your palm. Extend your arm straight up without bending the elbow. Release at forehead height. The ball should peak 6 inches above full racket reach." },
        { title: "Trophy Position", description: "As the toss goes up, bring the racket back and up. At the peak of the backswing, your elbow should be at shoulder height, the racket pointing up — this is the trophy position." },
        { title: "The Swing", description: "From the trophy position, drop the racket behind your back (racket drop), then drive up with your legs and rotate your core. The racket accelerates upward toward the ball." },
        { title: "Pronation & Contact", description: "Just before contact, pronate your forearm (rotate it inward). This turns the racket face to create power and spin. Contact the ball at full extension, slightly in front of your body." },
        { title: "Follow-Through", description: "The racket finishes on the opposite side of your body. Land on your front foot inside the baseline. Recover to ready position immediately." },
      ],
      commonMistakes: [
        "Inconsistent toss direction and height",
        "Using a forehand grip instead of continental",
        "Not bending the knees for leg drive",
        "Rushing the motion instead of loading properly",
        "Slapping the ball instead of pronating",
      ],
      recommendedDrills: [
        "Toss-only practice: 50 tosses to a target spot",
        "Trophy position holds (3 sets of 10 seconds)",
        "Serve from the knees (focus on pronation only)",
        "Baseline serving: 10 serves each to deuce/ad side targets",
      ],
      relatedLessonIds: ["les-1"],
    },
    createdAt: "2025-02-01T10:00:00Z",
    updatedAt: "2025-03-20T16:00:00Z",
  },
  {
    id: "les-4",
    title: "Footwork Fundamentals",
    slug: "footwork-fundamentals",
    description: "Move like a pro with proper court coverage, split steps, and recovery patterns.",
    categoryId: "cat-6",
    skillLevel: "beginner",
    tags: ["footwork", "movement", "agility", "split-step"],
    estimatedMinutes: 20,
    sortOrder: 4,
    isPublished: true,
    content: {
      explanation: "Good footwork is the foundation of every great tennis player. Without proper movement, even perfect stroke mechanics fall apart. The split step, lateral shuffle, crossover step, and recovery steps form the core movement vocabulary every player needs.",
      keyPoints: [
        "Split step before every shot your opponent hits",
        "Small adjustment steps are more important than big lunges",
        "Always recover to a tactically correct position — not always the center",
        "Load your outside leg to change direction efficiently",
        "Maintain a low center of gravity throughout rallies",
      ],
      steps: [
        { title: "The Split Step", description: "As your opponent begins their forward swing, perform a small hop, landing on the balls of both feet simultaneously. This pre-loads your muscles for explosive movement in any direction." },
        { title: "Lateral Movement", description: "Use shuffle steps for short distances. Keep feet parallel and never cross them. Maintain a wide base for balance." },
        { title: "Crossover Step", description: "For longer distances, use a crossover step: push off with the outside foot and cross the inside foot over. Then transition to shuffle steps as you approach the ball." },
        { title: "Recovery", description: "After hitting, push off the outside leg to start recovering. Use shuffle steps to return to your optimal court position based on where you hit the ball." },
      ],
      commonMistakes: [
        "Flat-footed between shots — no split step",
        "Taking too-large steps instead of many small adjustments",
        "Recovering to center every time instead of the correct position",
        "Standing up straight instead of staying low",
      ],
      recommendedDrills: [
        "Split step reaction drill (partner feeds, 3 min sets)",
        "Lateral shuffle through cone course (5 sets)",
        "Shadow tennis: full point footwork without a ball (2 min sets)",
        "Spider drill: touch all court corners from center (timed)",
      ],
      relatedLessonIds: [],
    },
    createdAt: "2025-02-05T10:00:00Z",
    updatedAt: "2025-03-12T11:00:00Z",
  },
  {
    id: "les-5",
    title: "Topspin Mastery",
    slug: "topspin-mastery",
    description: "Generate heavy topspin to control rallies and push opponents back.",
    categoryId: "cat-15",
    skillLevel: "intermediate",
    tags: ["topspin", "spin", "technique", "rally"],
    estimatedMinutes: 25,
    sortOrder: 5,
    isPublished: true,
    content: {
      explanation: "Topspin is the modern game's most important ball characteristic. It allows you to hit with high margins over the net while keeping the ball in play, forces opponents to hit from uncomfortable positions, and creates natural depth on your shots. Heavy topspin is achieved through racket acceleration on a low-to-high swing path.",
      keyPoints: [
        "Racket head speed is more important than arm strength",
        "The swing path must be steeply low-to-high",
        "A semi-western or western grip naturally promotes topspin",
        "Brush up the back of the ball — don't push through it",
        "Relaxed wrist allows natural windshield-wiper finish",
      ],
      steps: [
        { title: "Grip Setup", description: "Use at minimum a semi-western grip. For heavier topspin, experiment with a full western grip. The more western the grip, the more natural the topspin production." },
        { title: "Low Racket Drop", description: "During the forward swing, drop the racket head well below the incoming ball. The bigger the drop, the more spin potential you create." },
        { title: "Upward Acceleration", description: "Drive the racket head sharply upward through the ball. The swing path should be at roughly 45 degrees from low to high." },
        { title: "Windshield-Wiper Finish", description: "Allow the wrist to pronate naturally after contact, creating a windshield-wiper motion. The racket face rolls over the ball, adding extra spin." },
      ],
      commonMistakes: [
        "Pushing the ball instead of accelerating upward",
        "Tight grip preventing wrist pronation",
        "Not dropping the racket head low enough before contact",
        "Flat swing path — horizontal instead of vertical",
      ],
      recommendedDrills: [
        "Brush-up drill: hit over a high net tape (20 balls)",
        "Heavy topspin rally: aim 3 feet over the net (10 min)",
        "Short court topspin: mini-tennis with heavy spin (5 min)",
      ],
      relatedLessonIds: ["les-1"],
    },
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-03-18T09:00:00Z",
  },
  {
    id: "les-6",
    title: "Match Tactics for Intermediate Players",
    slug: "match-tactics-intermediate",
    description: "Develop a tactical game plan to win more matches through smart play.",
    categoryId: "cat-10",
    skillLevel: "intermediate",
    tags: ["tactics", "strategy", "match-play", "patterns"],
    estimatedMinutes: 30,
    sortOrder: 6,
    isPublished: true,
    content: {
      explanation: "Winning tennis matches isn't just about hitting better shots — it's about making better decisions. Tactical awareness means understanding patterns, recognizing your opponent's weaknesses, and constructing points with purpose rather than just reacting to every ball.",
      keyPoints: [
        "Play to your strengths more than attacking opponent weaknesses",
        "Rally crosscourt, attack down the line",
        "Change direction only when you have time and balance",
        "Use depth as your primary weapon — not pace",
        "Identify and exploit your opponent's patterns early in the match",
      ],
      steps: [
        { title: "Scouting Phase", description: "In the first 3-4 games, observe your opponent's tendencies. Note their weaker side, preferred patterns, and how they handle pressure." },
        { title: "Rally Construction", description: "Build points by hitting deep crosscourt shots. Wait for a short ball before attempting to change direction or approach the net." },
        { title: "Pressure Application", description: "When your opponent is pushed wide, hit behind them or to the open court. When they're deep, use drop shots or angles." },
        { title: "Closing Points", description: "After creating an advantage, commit to the finishing shot. Approach the net behind deep approach shots. Put away short balls with authority." },
      ],
      commonMistakes: [
        "Going for winners from neutral or defensive positions",
        "Not having a game plan — just hitting and hoping",
        "Ignoring opponent patterns and playing the same way regardless",
        "Changing a winning strategy when the opponent changes tactics",
      ],
      recommendedDrills: [
        "Point construction drill: crosscourt until short ball, then attack (15 min)",
        "Pattern play: serve + 1 with a planned second shot direction",
        "Match simulation: play sets with specific tactical goals",
      ],
      relatedLessonIds: ["les-4"],
    },
    createdAt: "2025-02-15T10:00:00Z",
    updatedAt: "2025-03-22T14:00:00Z",
  },
];

// ── Training Plans ──

const demoExercises: Exercise[] = [
  {
    id: "ex-1",
    sessionId: "sess-1",
    title: "Crosscourt Forehand Rally",
    description: "Rally consistently crosscourt using only forehands. Focus on depth and topspin. Aim to keep every ball past the service line.",
    durationMinutes: 15,
    category: "forehand",
    difficulty: "intermediate",
    tips: ["Stay sideways on the unit turn", "Watch the ball into the strings", "Follow through fully each time"],
    sortOrder: 1,
  },
  {
    id: "ex-2",
    sessionId: "sess-1",
    title: "Target Practice — Forehand Deep Corners",
    description: "Place targets (cones or towels) in both deep corners. Hit 10 forehands to each target, tracking accuracy.",
    sets: 4,
    reps: 10,
    restSeconds: 30,
    category: "forehand",
    difficulty: "intermediate",
    tips: ["Use full follow-through", "Don't sacrifice form for power", "Track your hit percentage"],
    sortOrder: 2,
  },
  {
    id: "ex-3",
    sessionId: "sess-1",
    title: "Approach Shot to Volley Drill",
    description: "Feed a mid-court ball, hit an approach shot down the line, then close to net for a volley finish.",
    durationMinutes: 10,
    category: "net-play",
    difficulty: "intermediate",
    tips: ["Split step before the volley", "Keep the approach deep", "Volley to the open court"],
    sortOrder: 3,
  },
];

const demoSessions: TrainingSession[] = [
  {
    id: "sess-1",
    planId: "plan-1",
    title: "Forehand Power & Consistency",
    description: "Technical session focused on building forehand reliability and controlled aggression.",
    sessionType: "technical",
    dayOfWeek: 1,
    date: "2025-04-07",
    durationMinutes: 90,
    exercises: demoExercises,
    warmup: "5 min dynamic stretching, 5 min mini-tennis rally",
    cooldown: "5 min static stretching, foam roll shoulders and forearm",
    coachNotes: "Focus on keeping the wrist relaxed through the take-back. If the forehand is spraying, slow down the swing and prioritize contact point.",
    sortOrder: 1,
    createdAt: "2025-04-01T10:00:00Z",
  },
  {
    id: "sess-2",
    planId: "plan-1",
    title: "Footwork & Court Coverage",
    description: "Movement session to improve lateral speed, recovery, and split step timing.",
    sessionType: "footwork",
    dayOfWeek: 2,
    date: "2025-04-08",
    durationMinutes: 60,
    exercises: [
      {
        id: "ex-4",
        sessionId: "sess-2",
        title: "Spider Drill",
        description: "Start at center mark. Sprint to each corner of the service boxes and back. Time each set.",
        sets: 5,
        restSeconds: 60,
        category: "footwork",
        difficulty: "intermediate",
        tips: ["Stay low", "Push off with the outside foot", "Touch the line with your hand"],
        sortOrder: 1,
      },
      {
        id: "ex-5",
        sessionId: "sess-2",
        title: "Split Step Reaction Drill",
        description: "Partner feeds random directions. Split step, react, and hit. Focus on the timing of the split step — it should happen as your partner makes contact.",
        durationMinutes: 15,
        category: "footwork",
        difficulty: "intermediate",
        tips: ["Land on both feet simultaneously", "Explode out of the split step", "Keep your eyes on the ball feeder"],
        sortOrder: 2,
      },
    ],
    warmup: "5 min jump rope, dynamic leg stretches",
    cooldown: "Calf and quad stretches, ankle circles",
    coachNotes: "If knees feel stressed, reduce spider drill sets to 3. Prioritize proper form over speed.",
    sortOrder: 2,
    createdAt: "2025-04-01T10:00:00Z",
  },
  {
    id: "sess-3",
    planId: "plan-1",
    title: "Serve Development",
    description: "Build serve consistency and introduce kick serve basics.",
    sessionType: "serve_practice",
    dayOfWeek: 4,
    date: "2025-04-10",
    durationMinutes: 75,
    exercises: [
      {
        id: "ex-6",
        sessionId: "sess-3",
        title: "Toss Consistency Practice",
        description: "Practice 30 tosses without hitting. Focus on consistent height and placement.",
        reps: 30,
        category: "serve",
        difficulty: "beginner",
        tips: ["Release at forehead height", "Keep the elbow straight", "Catch the ball at the peak — it should be in the right spot every time"],
        sortOrder: 1,
      },
      {
        id: "ex-7",
        sessionId: "sess-3",
        title: "Flat Serve — First Serves",
        description: "Hit 40 first serves. Track how many land in. Target: 60%+ in-rate.",
        reps: 40,
        category: "serve",
        difficulty: "intermediate",
        tips: ["Full leg drive", "Pronate aggressively", "Aim for the T first, then switch to wide"],
        sortOrder: 2,
      },
    ],
    warmup: "Shoulder band warm-up, light serving motion without a ball",
    cooldown: "Shoulder stretches, rotator cuff cool-down",
    coachNotes: "Shoulder tightness noted. Do extra warm-up and stop if pain increases.",
    sortOrder: 3,
    createdAt: "2025-04-01T10:00:00Z",
  },
  {
    id: "sess-4",
    planId: "plan-1",
    title: "Match Play Conditioning",
    description: "Conditioning session that simulates match intensity and duration.",
    sessionType: "conditioning",
    dayOfWeek: 5,
    date: "2025-04-11",
    durationMinutes: 60,
    exercises: [
      {
        id: "ex-8",
        sessionId: "sess-4",
        title: "Interval Court Sprints",
        description: "Sprint baseline to net and back. 20 seconds on, 40 seconds rest. Simulate point-to-point intensity.",
        sets: 8,
        restSeconds: 40,
        category: "conditioning",
        difficulty: "intermediate",
        tips: ["Stay light on your feet", "Decelerate under control", "Breathe rhythmically during rest"],
        sortOrder: 1,
      },
    ],
    warmup: "10 min light jog and dynamic stretching",
    cooldown: "Walk 5 min, full body stretch",
    coachNotes: "Keep heart rate in zone 3-4. If feeling fatigued from serve session, reduce sets to 5.",
    sortOrder: 4,
    createdAt: "2025-04-01T10:00:00Z",
  },
];

export const demoTrainingPlan: TrainingPlan = {
  id: "plan-1",
  userId: "usr-1",
  title: "Intermediate Development — Week 15",
  description: "Focused on forehand improvement, serve consistency, and building match-ready conditioning. This week emphasizes technical refinement with controlled intensity due to minor shoulder concern.",
  period: "weekly",
  startDate: "2025-04-07",
  endDate: "2025-04-13",
  focusAreas: ["Forehand", "Serve", "Footwork", "Conditioning"],
  skillLevel: "intermediate",
  intensity: "moderate",
  sessions: demoSessions,
  isActive: true,
  generatedBy: "ai",
  createdAt: "2025-04-01T08:00:00Z",
  updatedAt: "2025-04-07T06:00:00Z",
};

// ── Progress ──

export const progressLogs: ProgressLog[] = [
  { id: "prog-1", userId: "usr-1", sessionId: "sess-1", date: "2025-04-07", status: "completed", selfRating: 4, notes: "Forehand felt solid today. Contact point was consistent. Need to work on recovery step after wide balls.", focusAreas: ["Forehand"], durationMinutes: 85, createdAt: "2025-04-07T18:00:00Z" },
  { id: "prog-2", userId: "usr-1", sessionId: "sess-2", date: "2025-04-08", status: "completed", selfRating: 3, notes: "Footwork was sluggish at start but improved. Split step timing getting better.", focusAreas: ["Footwork"], durationMinutes: 55, createdAt: "2025-04-08T17:30:00Z" },
  { id: "prog-3", userId: "usr-1", date: "2025-04-09", status: "skipped", notes: "Rest day — shoulder tightness", focusAreas: [], createdAt: "2025-04-09T20:00:00Z" },
  { id: "prog-4", userId: "usr-1", sessionId: "sess-3", date: "2025-04-10", status: "partial", selfRating: 3, notes: "Did toss practice and 20 flat serves. Stopped early — shoulder felt uncomfortable after 30 minutes.", focusAreas: ["Serve"], durationMinutes: 35, createdAt: "2025-04-10T16:00:00Z" },
];

// ── User Goals ──

export const userGoals: UserGoal[] = [
  { id: "goal-1", userId: "usr-1", title: "70% first serve percentage", description: "Achieve consistent 70%+ first serve in-rate during practice sets", isCompleted: false, targetDate: "2025-06-01", createdAt: "2025-03-01T10:00:00Z" },
  { id: "goal-2", userId: "usr-1", title: "Win club ladder match", description: "Win a match against a player ranked above me in the club ladder", isCompleted: false, targetDate: "2025-05-15", createdAt: "2025-03-01T10:00:00Z" },
  { id: "goal-3", userId: "usr-1", title: "Master topspin forehand", description: "Consistently hit heavy topspin forehands with depth control", isCompleted: false, targetDate: "2025-07-01", createdAt: "2025-03-15T10:00:00Z" },
];

// ── Admin Dashboard Stats ──

export const adminDashboardStats: AdminDashboardStats = {
  totalSources: sources.length,
  activeSources: sources.filter((s) => s.status === "active").length,
  pendingIngestion: sources.filter((s) => s.ingestionState === "pending" || s.ingestionState === "processing").length,
  totalUsers: 47,
  totalPlans: 156,
  recentUploads: sources.slice(0, 4),
  recentUpdates: sources.slice(0, 3),
  systemStatus: "healthy",
};

// ── User Dashboard Data ──

export const userDashboardData: UserDashboardData = {
  user: demoUser,
  profile: demoProfile,
  activePlan: demoTrainingPlan,
  todaySession: demoSessions[2], // serve session for April 10
  weeklyProgress: progressLogs,
  recentGoals: userGoals,
  recommendedLessons: [lessons[0], lessons[2], lessons[4]],
  stats: {
    totalSessions: 48,
    completedSessions: 41,
    currentStreak: 2,
    focusAreaBreakdown: {
      Forehand: 14,
      Backhand: 8,
      Serve: 10,
      Footwork: 9,
      Conditioning: 7,
      Tactics: 5,
    },
  },
};
