// ============================================================
// MATCHPOINT — Procedural anatomy: region-tagged body parts
// ============================================================
// A smooth stylized mannequin: non-interactive "mass" meshes form a
// continuous body silhouette, and thinner clickable "pads" sit on the
// surface mapped to canonical region ids (lib/doc-checkin/regions).
// This is the assetless v1; a real Z-Anatomy / BodyParts3D GLB replaces
// it via asset-manifest.ts (see anatomy/README.md).
//
// Coordinate space: Y up, model faces +Z (toward camera). Height runs
// roughly y = -0.95 (feet) to +0.9 (head). Model's right is at negative
// X, so x < 0 → anatomical "right", x > 0 → "left".
// ============================================================

import type { BodySide } from "@/lib/doc-checkin/regions";

export type PartKind = "capsule" | "box" | "sphere";

export interface BodyPart {
  key: string;
  regionId: string;
  side: BodySide;
  kind: PartKind;
  /** capsule=[radius,length], box=[w,h,d], sphere=[radius]. */
  args: number[];
  position: [number, number, number];
  rotation?: [number, number, number];
  /** Non-uniform scale to sculpt ellipsoids / flattened pads. */
  scale?: [number, number, number];
  softTissue?: boolean;
  boneOnly?: boolean;
}

function mirror(p: BodyPart): BodyPart {
  const side: BodySide = p.side === "left" ? "right" : "left";
  return {
    ...p,
    key: p.key.replace(/-l$/, "-r"),
    side,
    position: [-p.position[0], p.position[1], p.position[2]],
    rotation: p.rotation ? [p.rotation[0], -p.rotation[1], -p.rotation[2]] : undefined,
  };
}

// Left-side (x > 0) clickable pads; right generated by mirror().
const LEFT_PAIRED: BodyPart[] = [
  // Shoulder girdle — round caps blending torso into arms
  { key: "shoulder-l", regionId: "shoulder", side: "left", kind: "sphere", args: [0.085], position: [0.185, 0.54, 0.01] },
  { key: "trapezius-l", regionId: "trapezius", side: "left", kind: "sphere", args: [0.07], position: [0.075, 0.56, -0.05], scale: [1.3, 0.7, 0.7], softTissue: true },
  { key: "scapula-l", regionId: "scapula", side: "left", kind: "sphere", args: [0.075], position: [0.085, 0.44, -0.11], scale: [1, 1.3, 0.4] },
  { key: "lat-l", regionId: "lat", side: "left", kind: "sphere", args: [0.075], position: [0.12, 0.34, -0.05], scale: [0.8, 1.5, 0.9], softTissue: true },
  // Chest / oblique (front)
  { key: "chest-l", regionId: "chest", side: "left", kind: "sphere", args: [0.08], position: [0.055, 0.47, 0.09], scale: [1.1, 0.9, 0.6], softTissue: true },
  { key: "oblique-l", regionId: "oblique", side: "left", kind: "sphere", args: [0.06], position: [0.1, 0.28, 0.05], scale: [0.8, 1.5, 0.9], softTissue: true },
  // Arm
  { key: "upperArm-l", regionId: "upperArm", side: "left", kind: "capsule", args: [0.052, 0.2], position: [0.215, 0.38, 0.005], rotation: [0, 0, 0.06] },
  { key: "elbow-l", regionId: "elbow", side: "left", kind: "sphere", args: [0.05], position: [0.235, 0.23, 0.005] },
  { key: "forearm-l", regionId: "forearm", side: "left", kind: "capsule", args: [0.044, 0.19], position: [0.25, 0.09, 0.015], rotation: [0, 0, 0.04] },
  { key: "wrist-l", regionId: "wrist", side: "left", kind: "sphere", args: [0.052], position: [0.262, -0.05, 0.025], scale: [1, 1.3, 0.8] },
  // Hip / glute
  { key: "hip-l", regionId: "hip", side: "left", kind: "sphere", args: [0.075], position: [0.085, 0.07, 0.05], scale: [1, 1, 0.7], softTissue: true },
  { key: "glute-l", regionId: "glute", side: "left", kind: "sphere", args: [0.085], position: [0.08, 0.02, -0.08], scale: [1, 1, 0.9], softTissue: true },
  // Leg — thigh & lower-leg masses + front/back pads
  { key: "thigh-l", regionId: "quad", side: "left", kind: "capsule", args: [0.078, 0.26], position: [0.085, -0.18, 0], softTissue: true },
  { key: "hamstring-l", regionId: "hamstring", side: "left", kind: "sphere", args: [0.06], position: [0.085, -0.22, -0.06], scale: [1, 1.9, 0.7], softTissue: true },
  { key: "knee-l", regionId: "knee", side: "left", kind: "sphere", args: [0.062], position: [0.088, -0.42, 0.01] },
  { key: "shin-l", regionId: "shin", side: "left", kind: "capsule", args: [0.05, 0.24], position: [0.09, -0.62, 0.01] },
  { key: "calf-l", regionId: "calf", side: "left", kind: "sphere", args: [0.052], position: [0.09, -0.58, -0.05], scale: [1, 1.9, 0.9], softTissue: true },
  { key: "achilles-l", regionId: "achilles", side: "left", kind: "capsule", args: [0.03, 0.1], position: [0.09, -0.8, -0.05] },
  { key: "ankle-l", regionId: "ankle", side: "left", kind: "sphere", args: [0.05], position: [0.09, -0.9, 0.01] },
];

// Centered clickable pads.
const CENTER: BodyPart[] = [
  { key: "neck", regionId: "neck", side: "center", kind: "capsule", args: [0.052, 0.1], position: [0, 0.66, 0] },
  { key: "abdomen", regionId: "abdomen", side: "center", kind: "sphere", args: [0.1], position: [0, 0.29, 0.06], scale: [1, 1.3, 0.5], softTissue: true },
  { key: "upperBack", regionId: "upperBack", side: "center", kind: "sphere", args: [0.12], position: [0, 0.46, -0.09], scale: [1.2, 1.1, 0.4] },
  { key: "lowerBack", regionId: "lowerBack", side: "center", kind: "sphere", args: [0.11], position: [0, 0.27, -0.09], scale: [1.1, 1, 0.4] },
];

export const BODY_PARTS: BodyPart[] = [
  ...CENTER,
  ...LEFT_PAIRED,
  ...LEFT_PAIRED.map(mirror),
];

// Non-interactive masses that give the continuous body silhouette.
export interface DecorPart {
  key: string;
  kind: PartKind;
  args: number[];
  position: [number, number, number];
  scale?: [number, number, number];
  boneOnly?: boolean;
  softTissue?: boolean;
}

export const DECOR_PARTS: DecorPart[] = [
  { key: "head", kind: "sphere", args: [0.115], position: [0, 0.81, 0.01], scale: [0.92, 1.05, 1] },
  // Torso: three overlapping ellipsoids → tapered chest → waist → pelvis.
  { key: "thorax", kind: "sphere", args: [0.17], position: [0, 0.47, 0], scale: [1.05, 1.15, 0.72] },
  { key: "waist", kind: "sphere", args: [0.14], position: [0, 0.29, 0], scale: [0.98, 1.1, 0.7] },
  { key: "pelvis", kind: "sphere", args: [0.15], position: [0, 0.09, 0], scale: [1.08, 0.95, 0.74] },
  // Feet
  { key: "foot-l", kind: "box", args: [0.07, 0.05, 0.16], position: [0.09, -0.95, 0.05] },
  { key: "foot-r", kind: "box", args: [0.07, 0.05, 0.16], position: [-0.09, -0.95, 0.05] },
  // Spine (skeleton layer only)
  { key: "spine", kind: "capsule", args: [0.03, 0.5], position: [0, 0.4, -0.07], boneOnly: true },
];
