// ============================================================
// MATCHPOINT — Procedural anatomy: region-tagged body parts
// ============================================================
// Each entry is one clickable mesh mapped to a canonical region id
// (see lib/doc-checkin/regions). This procedural mannequin is the
// v1 asset; a real Z-Anatomy / BodyParts3D GLB can replace it later
// (see anatomy/README.md) by mapping its mesh names to these ids.
//
// Coordinate space: Y up, model faces +Z (toward camera). Height runs
// roughly y = -0.95 (feet) to +0.9 (head). Model's right side is at
// negative X, so x < 0 → anatomical "right", x > 0 → "left".
// ============================================================

import type { BodySide } from "@/lib/doc-checkin/regions";

export type PartKind = "capsule" | "box" | "sphere";

export interface BodyPart {
  key: string; // unique mesh key
  regionId: string; // canonical region id
  side: BodySide;
  kind: PartKind;
  /** Geometry args: capsule=[radius,length], box=[w,h,d], sphere=[radius]. */
  args: number[];
  position: [number, number, number];
  rotation?: [number, number, number];
  /** true = flesh only (hidden when skeleton layer active). */
  softTissue?: boolean;
  /** true = bone only (hidden when muscle layer active). Default: shown in both. */
  boneOnly?: boolean;
}

// Mirror a part to the other side (flips X and swaps side label).
function mirror(p: BodyPart): BodyPart {
  const side: BodySide = p.side === "left" ? "right" : "left";
  return {
    ...p,
    key: p.key.replace(/-l$/, "-r"),
    side,
    position: [-p.position[0], p.position[1], p.position[2]],
    rotation: p.rotation ? [p.rotation[0], -p.rotation[1], -p.rotation[2]] : undefined,
  };
}

// Left-side (x > 0) definitions; right side generated by mirror().
const LEFT_PAIRED: BodyPart[] = [
  // Shoulder girdle
  { key: "shoulder-l", regionId: "shoulder", side: "left", kind: "sphere", args: [0.075], position: [0.2, 0.5, 0] },
  { key: "trapezius-l", regionId: "trapezius", side: "left", kind: "box", args: [0.11, 0.09, 0.08], position: [0.09, 0.52, -0.05] },
  { key: "scapula-l", regionId: "scapula", side: "left", kind: "box", args: [0.1, 0.13, 0.04], position: [0.1, 0.4, -0.1] },
  { key: "lat-l", regionId: "lat", side: "left", kind: "box", args: [0.07, 0.16, 0.12], position: [0.14, 0.3, -0.03] },
  // Chest / oblique (front)
  { key: "chest-l", regionId: "chest", side: "left", kind: "box", args: [0.11, 0.13, 0.09], position: [0.07, 0.42, 0.05], softTissue: true },
  { key: "oblique-l", regionId: "oblique", side: "left", kind: "box", args: [0.06, 0.14, 0.1], position: [0.12, 0.26, 0.03], softTissue: true },
  // Arm
  { key: "upperArm-l", regionId: "upperArm", side: "left", kind: "capsule", args: [0.05, 0.2], position: [0.24, 0.36, 0], rotation: [0, 0, 0.08] },
  { key: "elbow-l", regionId: "elbow", side: "left", kind: "sphere", args: [0.048], position: [0.26, 0.22, 0] },
  { key: "forearm-l", regionId: "forearm", side: "left", kind: "capsule", args: [0.042, 0.2], position: [0.28, 0.07, 0.01], rotation: [0, 0, 0.05] },
  { key: "wrist-l", regionId: "wrist", side: "left", kind: "sphere", args: [0.05], position: [0.3, -0.06, 0.02] },
  // Hip / glute
  { key: "hip-l", regionId: "hip", side: "left", kind: "sphere", args: [0.07], position: [0.1, 0.06, 0.03], softTissue: true },
  { key: "glute-l", regionId: "glute", side: "left", kind: "box", args: [0.11, 0.11, 0.09], position: [0.1, 0.0, -0.07], softTissue: true },
  // Leg
  { key: "quad-l", regionId: "quad", side: "left", kind: "capsule", args: [0.06, 0.24], position: [0.1, -0.2, 0.03], softTissue: true },
  { key: "hamstring-l", regionId: "hamstring", side: "left", kind: "capsule", args: [0.06, 0.22], position: [0.1, -0.2, -0.06], softTissue: true },
  { key: "knee-l", regionId: "knee", side: "left", kind: "sphere", args: [0.06], position: [0.1, -0.42, 0] },
  { key: "shin-l", regionId: "shin", side: "left", kind: "capsule", args: [0.045, 0.24], position: [0.1, -0.62, 0.03] },
  { key: "calf-l", regionId: "calf", side: "left", kind: "capsule", args: [0.055, 0.2], position: [0.1, -0.62, -0.05], softTissue: true },
  { key: "achilles-l", regionId: "achilles", side: "left", kind: "capsule", args: [0.028, 0.1], position: [0.1, -0.8, -0.05] },
  { key: "ankle-l", regionId: "ankle", side: "left", kind: "sphere", args: [0.05], position: [0.1, -0.88, 0.02] },
];

// Centered (unpaired) parts.
const CENTER: BodyPart[] = [
  { key: "neck", regionId: "neck", side: "center", kind: "capsule", args: [0.05, 0.08], position: [0, 0.63, 0] },
  { key: "abdomen", regionId: "abdomen", side: "center", kind: "box", args: [0.16, 0.16, 0.12], position: [0, 0.27, 0.02], softTissue: true },
  { key: "upperBack", regionId: "upperBack", side: "center", kind: "box", args: [0.18, 0.16, 0.05], position: [0, 0.42, -0.1] },
  { key: "lowerBack", regionId: "lowerBack", side: "center", kind: "box", args: [0.15, 0.13, 0.05], position: [0, 0.22, -0.1] },
];

export const BODY_PARTS: BodyPart[] = [
  ...CENTER,
  ...LEFT_PAIRED,
  ...LEFT_PAIRED.map(mirror),
];

// Non-interactive decorative meshes (head, spine column) for silhouette.
export interface DecorPart {
  key: string;
  kind: PartKind;
  args: number[];
  position: [number, number, number];
  boneOnly?: boolean;
  softTissue?: boolean;
}

export const DECOR_PARTS: DecorPart[] = [
  { key: "head", kind: "sphere", args: [0.12], position: [0, 0.79, 0.01] },
  { key: "spine", kind: "capsule", args: [0.028, 0.5], position: [0, 0.4, -0.08], boneOnly: true },
];
